// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ChapterHandler is an autogenerated mock type for the ChapterHandler type
type ChapterHandler struct {
	mock.Mock
}

// AddChapterH provides a mock function with given fields: c
func (_m *ChapterHandler) AddChapterH(c *gin.Context) {
	_m.Called(c)
}

// DeleteChapterH provides a mock function with given fields: c
func (_m *ChapterHandler) DeleteChapterH(c *gin.Context) {
	_m.Called(c)
}

// GetChapterByIDH provides a mock function with given fields: c
func (_m *ChapterHandler) GetChapterByIDH(c *gin.Context) {
	_m.Called(c)
}

// GetChaptersByCourseIDH provides a mock function with given fields: c
func (_m *ChapterHandler) GetChaptersByCourseIDH(c *gin.Context) {
	_m.Called(c)
}

// GetChaptersH provides a mock function with given fields: c
func (_m *ChapterHandler) GetChaptersH(c *gin.Context) {
	_m.Called(c)
}

// UpdateChapterH provides a mock function with given fields: c
func (_m *ChapterHandler) UpdateChapterH(c *gin.Context) {
	_m.Called(c)
}

// NewChapterHandler creates a new instance of ChapterHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChapterHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChapterHandler {
	mock := &ChapterHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
