// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "MainService/entities"

	mock "github.com/stretchr/testify/mock"
)

// ChapterRepository is an autogenerated mock type for the ChapterRepository type
type ChapterRepository struct {
	mock.Mock
}

// AddChapter provides a mock function with given fields: chapter
func (_m *ChapterRepository) AddChapter(chapter entities.Chapter) (uint, error) {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for AddChapter")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Chapter) (uint, error)); ok {
		return rf(chapter)
	}
	if rf, ok := ret.Get(0).(func(entities.Chapter) uint); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(entities.Chapter) error); ok {
		r1 = rf(chapter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteChapter provides a mock function with given fields: chapterID
func (_m *ChapterRepository) DeleteChapter(chapterID uint) error {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(chapterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChapterByID provides a mock function with given fields: chapterID
func (_m *ChapterRepository) GetChapterByID(chapterID uint) (entities.Chapter, error) {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for GetChapterByID")
	}

	var r0 entities.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (entities.Chapter, error)); ok {
		return rf(chapterID)
	}
	if rf, ok := ret.Get(0).(func(uint) entities.Chapter); ok {
		r0 = rf(chapterID)
	} else {
		r0 = ret.Get(0).(entities.Chapter)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChapters provides a mock function with no fields
func (_m *ChapterRepository) GetChapters() ([]entities.Chapter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChapters")
	}

	var r0 []entities.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Chapter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Chapter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChaptersByCourseID provides a mock function with given fields: courseID
func (_m *ChapterRepository) GetChaptersByCourseID(courseID uint) ([]entities.Chapter, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetChaptersByCourseID")
	}

	var r0 []entities.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]entities.Chapter, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) []entities.Chapter); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChapter provides a mock function with given fields: updChapter
func (_m *ChapterRepository) UpdateChapter(updChapter entities.Chapter) error {
	ret := _m.Called(updChapter)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Chapter) error); ok {
		r0 = rf(updChapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChapterRepository creates a new instance of ChapterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChapterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChapterRepository {
	mock := &ChapterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
