// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "MainService/entities"
	entitiesDTO "MainService/entitiesDTO"

	mock "github.com/stretchr/testify/mock"
)

// ChapterService is an autogenerated mock type for the ChapterService type
type ChapterService struct {
	mock.Mock
}

// AddChapterS provides a mock function with given fields: chapter
func (_m *ChapterService) AddChapterS(chapter entities.Chapter) (uint, error) {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for AddChapterS")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Chapter) (uint, error)); ok {
		return rf(chapter)
	}
	if rf, ok := ret.Get(0).(func(entities.Chapter) uint); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(entities.Chapter) error); ok {
		r1 = rf(chapter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteChapterS provides a mock function with given fields: chapterID
func (_m *ChapterService) DeleteChapterS(chapterID uint) error {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapterS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(chapterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChapterByIDS provides a mock function with given fields: chapterID
func (_m *ChapterService) GetChapterByIDS(chapterID uint) (*entitiesDTO.ChapterDTO, error) {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for GetChapterByIDS")
	}

	var r0 *entitiesDTO.ChapterDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entitiesDTO.ChapterDTO, error)); ok {
		return rf(chapterID)
	}
	if rf, ok := ret.Get(0).(func(uint) *entitiesDTO.ChapterDTO); ok {
		r0 = rf(chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitiesDTO.ChapterDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChaptersByCourseIDS provides a mock function with given fields: courseID
func (_m *ChapterService) GetChaptersByCourseIDS(courseID uint) ([]entitiesDTO.ChapterDTO, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetChaptersByCourseIDS")
	}

	var r0 []entitiesDTO.ChapterDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]entitiesDTO.ChapterDTO, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) []entitiesDTO.ChapterDTO); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entitiesDTO.ChapterDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChaptersS provides a mock function with no fields
func (_m *ChapterService) GetChaptersS() ([]entitiesDTO.ChapterDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChaptersS")
	}

	var r0 []entitiesDTO.ChapterDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entitiesDTO.ChapterDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entitiesDTO.ChapterDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entitiesDTO.ChapterDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChapterS provides a mock function with given fields: updChapter
func (_m *ChapterService) UpdateChapterS(updChapter entitiesDTO.ChapterDTO) error {
	ret := _m.Called(updChapter)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChapterS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entitiesDTO.ChapterDTO) error); ok {
		r0 = rf(updChapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChapterService creates a new instance of ChapterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChapterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChapterService {
	mock := &ChapterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
