// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "MainService/entities"

	mock "github.com/stretchr/testify/mock"
)

// CourseRepository is an autogenerated mock type for the CourseRepository type
type CourseRepository struct {
	mock.Mock
}

// AddCourse provides a mock function with given fields: course
func (_m *CourseRepository) AddCourse(course entities.Course) (uint, error) {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for AddCourse")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Course) (uint, error)); ok {
		return rf(course)
	}
	if rf, ok := ret.Get(0).(func(entities.Course) uint); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(entities.Course) error); ok {
		r1 = rf(course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCourse provides a mock function with given fields: courseID
func (_m *CourseRepository) DeleteCourse(courseID uint) error {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCourseByID provides a mock function with given fields: courseID
func (_m *CourseRepository) GetCourseByID(courseID uint) (entities.Course, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseByID")
	}

	var r0 entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (entities.Course, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) entities.Course); ok {
		r0 = rf(courseID)
	} else {
		r0 = ret.Get(0).(entities.Course)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourses provides a mock function with no fields
func (_m *CourseRepository) GetCourses() ([]entities.Course, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCourses")
	}

	var r0 []entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Course, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Course); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Course)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCurse provides a mock function with given fields: updCourse
func (_m *CourseRepository) UpdateCurse(updCourse entities.Course) error {
	ret := _m.Called(updCourse)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCurse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Course) error); ok {
		r0 = rf(updCourse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
