// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// CourseHandler is an autogenerated mock type for the CourseHandler type
type CourseHandler struct {
	mock.Mock
}

// AddCourseH provides a mock function with given fields: c
func (_m *CourseHandler) AddCourseH(c *gin.Context) {
	_m.Called(c)
}

// DeleteCourseH provides a mock function with given fields: c
func (_m *CourseHandler) DeleteCourseH(c *gin.Context) {
	_m.Called(c)
}

// GetCourseByIDH provides a mock function with given fields: c
func (_m *CourseHandler) GetCourseByIDH(c *gin.Context) {
	_m.Called(c)
}

// GetCourseH provides a mock function with given fields: c
func (_m *CourseHandler) GetCourseH(c *gin.Context) {
	_m.Called(c)
}

// UpdateCourseH provides a mock function with given fields: c
func (_m *CourseHandler) UpdateCourseH(c *gin.Context) {
	_m.Called(c)
}

// NewCourseHandler creates a new instance of CourseHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseHandler {
	mock := &CourseHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
