// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "MainService/entities"
	entitiesDTO "MainService/entitiesDTO"

	mock "github.com/stretchr/testify/mock"
)

// CourseService is an autogenerated mock type for the CourseService type
type CourseService struct {
	mock.Mock
}

// AddCourseS provides a mock function with given fields: course
func (_m *CourseService) AddCourseS(course entities.Course) (uint, error) {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for AddCourseS")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Course) (uint, error)); ok {
		return rf(course)
	}
	if rf, ok := ret.Get(0).(func(entities.Course) uint); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(entities.Course) error); ok {
		r1 = rf(course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCourseS provides a mock function with given fields: courseID
func (_m *CourseService) DeleteCourseS(courseID uint) error {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourseS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCourseByIDS provides a mock function with given fields: courseID
func (_m *CourseService) GetCourseByIDS(courseID uint) (*entitiesDTO.CourseDTO, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseByIDS")
	}

	var r0 *entitiesDTO.CourseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entitiesDTO.CourseDTO, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) *entitiesDTO.CourseDTO); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitiesDTO.CourseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCoursesS provides a mock function with no fields
func (_m *CourseService) GetCoursesS() ([]entitiesDTO.CourseDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCoursesS")
	}

	var r0 []entitiesDTO.CourseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entitiesDTO.CourseDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entitiesDTO.CourseDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entitiesDTO.CourseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCurseS provides a mock function with given fields: updCourse
func (_m *CourseService) UpdateCurseS(updCourse entitiesDTO.CourseDTO) error {
	ret := _m.Called(updCourse)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCurseS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entitiesDTO.CourseDTO) error); ok {
		r0 = rf(updCourse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseService creates a new instance of CourseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseService {
	mock := &CourseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
