// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "MainService/entities"
	entitiesDTO "MainService/entitiesDTO"

	mock "github.com/stretchr/testify/mock"
)

// LessonService is an autogenerated mock type for the LessonService type
type LessonService struct {
	mock.Mock
}

// AddLessonS provides a mock function with given fields: lesson
func (_m *LessonService) AddLessonS(lesson entities.Lesson) (uint, error) {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for AddLessonS")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Lesson) (uint, error)); ok {
		return rf(lesson)
	}
	if rf, ok := ret.Get(0).(func(entities.Lesson) uint); ok {
		r0 = rf(lesson)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(entities.Lesson) error); ok {
		r1 = rf(lesson)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLessonS provides a mock function with given fields: lessonID
func (_m *LessonService) DeleteLessonS(lessonID uint) error {
	ret := _m.Called(lessonID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLessonS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(lessonID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLessonByIDS provides a mock function with given fields: lessonID
func (_m *LessonService) GetLessonByIDS(lessonID uint) (*entitiesDTO.LessonDTO, error) {
	ret := _m.Called(lessonID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonByIDS")
	}

	var r0 *entitiesDTO.LessonDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entitiesDTO.LessonDTO, error)); ok {
		return rf(lessonID)
	}
	if rf, ok := ret.Get(0).(func(uint) *entitiesDTO.LessonDTO); ok {
		r0 = rf(lessonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitiesDTO.LessonDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLessonsByChapterIDS provides a mock function with given fields: chapterID
func (_m *LessonService) GetLessonsByChapterIDS(chapterID uint) ([]entitiesDTO.LessonDTO, error) {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonsByChapterIDS")
	}

	var r0 []entitiesDTO.LessonDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]entitiesDTO.LessonDTO, error)); ok {
		return rf(chapterID)
	}
	if rf, ok := ret.Get(0).(func(uint) []entitiesDTO.LessonDTO); ok {
		r0 = rf(chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entitiesDTO.LessonDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLessonsS provides a mock function with no fields
func (_m *LessonService) GetLessonsS() ([]entitiesDTO.LessonDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLessonsS")
	}

	var r0 []entitiesDTO.LessonDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entitiesDTO.LessonDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entitiesDTO.LessonDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entitiesDTO.LessonDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLessonS provides a mock function with given fields: updLesson
func (_m *LessonService) UpdateLessonS(updLesson entitiesDTO.LessonDTO) error {
	ret := _m.Called(updLesson)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLessonS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entitiesDTO.LessonDTO) error); ok {
		r0 = rf(updLesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLessonService creates a new instance of LessonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLessonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LessonService {
	mock := &LessonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
