// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// LessonHandler is an autogenerated mock type for the LessonHandler type
type LessonHandler struct {
	mock.Mock
}

// AddLessonH provides a mock function with given fields: c
func (_m *LessonHandler) AddLessonH(c *gin.Context) {
	_m.Called(c)
}

// DeleteLessonH provides a mock function with given fields: c
func (_m *LessonHandler) DeleteLessonH(c *gin.Context) {
	_m.Called(c)
}

// GetLessonByIDH provides a mock function with given fields: c
func (_m *LessonHandler) GetLessonByIDH(c *gin.Context) {
	_m.Called(c)
}

// GetLessonsByChapterIDH provides a mock function with given fields: c
func (_m *LessonHandler) GetLessonsByChapterIDH(c *gin.Context) {
	_m.Called(c)
}

// GetLessonsH provides a mock function with given fields: c
func (_m *LessonHandler) GetLessonsH(c *gin.Context) {
	_m.Called(c)
}

// UpdateLessonH provides a mock function with given fields: c
func (_m *LessonHandler) UpdateLessonH(c *gin.Context) {
	_m.Called(c)
}

// NewLessonHandler creates a new instance of LessonHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLessonHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *LessonHandler {
	mock := &LessonHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
