// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "MainService/entities"

	mock "github.com/stretchr/testify/mock"
)

// LessonRepository is an autogenerated mock type for the LessonRepository type
type LessonRepository struct {
	mock.Mock
}

// AddLesson provides a mock function with given fields: lesson
func (_m *LessonRepository) AddLesson(lesson entities.Lesson) (uint, error) {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for AddLesson")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Lesson) (uint, error)); ok {
		return rf(lesson)
	}
	if rf, ok := ret.Get(0).(func(entities.Lesson) uint); ok {
		r0 = rf(lesson)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(entities.Lesson) error); ok {
		r1 = rf(lesson)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLesson provides a mock function with given fields: lessonID
func (_m *LessonRepository) DeleteLesson(lessonID uint) error {
	ret := _m.Called(lessonID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(lessonID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLessonByID provides a mock function with given fields: lessonID
func (_m *LessonRepository) GetLessonByID(lessonID uint) (entities.Lesson, error) {
	ret := _m.Called(lessonID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonByID")
	}

	var r0 entities.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (entities.Lesson, error)); ok {
		return rf(lessonID)
	}
	if rf, ok := ret.Get(0).(func(uint) entities.Lesson); ok {
		r0 = rf(lessonID)
	} else {
		r0 = ret.Get(0).(entities.Lesson)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLessons provides a mock function with no fields
func (_m *LessonRepository) GetLessons() ([]entities.Lesson, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLessons")
	}

	var r0 []entities.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Lesson, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Lesson); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLessonsByChapterID provides a mock function with given fields: chapterID
func (_m *LessonRepository) GetLessonsByChapterID(chapterID uint) ([]entities.Lesson, error) {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonsByChapterID")
	}

	var r0 []entities.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]entities.Lesson, error)); ok {
		return rf(chapterID)
	}
	if rf, ok := ret.Get(0).(func(uint) []entities.Lesson); ok {
		r0 = rf(chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLesson provides a mock function with given fields: updLesson
func (_m *LessonRepository) UpdateLesson(updLesson entities.Lesson) error {
	ret := _m.Called(updLesson)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Lesson) error); ok {
		r0 = rf(updLesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLessonRepository creates a new instance of LessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LessonRepository {
	mock := &LessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
